yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст постов',
        help_text='Любой текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор')
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Из уже существующих')

    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Модель Post'
        verbose_name_plural = 'Модель Post'


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(
        max_length=255,
        unique=True,
        verbose_name='Слаг поста')
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост комментария')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария')
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст нового комментария')
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        db_index=False)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        db_index=False)

    class Meta:
        unique_together = ('user',
                           'author',)

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)
        help_text = {'text': 'Любой текст', 'group': 'Из уже существующих'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_text = {'text': 'Текст нового комментария'}

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .utils import get_page_context
from django.views.decorators.cache import cache_page


@cache_page(20, key_prefix="index_page")
def index(request):
    """Выводит шаблон главной страницы"""
    context = get_page_context(Post.objects.all(), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Выводит шаблон с группами постов"""
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(get_page_context(
        Post.objects.all().filter(group=group), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = (request.user.is_authenticated) and (
        Follow.objects.filter(user=request.user, author=author).exists())
    context = {
        'following': following,
        'author': author,
    }
    context.update(get_page_context(author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if not form.is_valid():
        return render(request, "posts/create_post.html", {"form": form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect("posts:profile", request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    is_edit = True
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {
                  'post': post, 'form': form, 'is_edit': is_edit})


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    context = get_page_context(Post.objects.filter(
        author__following__user=request.user), request)
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    user = request.user
    author = User.objects.get(username=username)
    if_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not if_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
                          
{% if not is_edit %}             
<title>Добавить запись</title>
{% else %} 
<title>Редактировать запись</title>
{% endif %}                  
{% endblock %} 
{% block content %}
{% load user_filters%}           <!--- Загружаем фильтры из приложения core -->
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">              
              {% if not is_edit %}                                
                Добавить запись         
              {% else %}              
                Редактировать запись
             {% endif %}
            </div>
            <div class="card-body">                                
                    {% if form.errors %} 
                        {% for field in form %} 
                          {% for error in form.errors %}
                              <div class="alert alert-danger" role="alert">
                                {{ error|escape }}
                              </div>
                          {% endfor %}
                       {% endfor %}
                       {% for error in form.non_field_errors %}
                       <div class="alert alert-danger">
                         {{ error|escape }}
                       </div>
                       {% endfor %}
                    {% endif %}
                {% include 'includes/post_form.html' %}    
            </div> 
        </div> 
    </div> 
</div> 
{% endblock %}  

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}<title>Лента подписки</title>{% endblock %} 
{% block header %}Лента подписки{% endblock %}
{% block content %}
{% include 'includes/switcher.html' %}  
<h3>Лента подписки</h3>
{% for post in page_obj %}

{% include 'includes/posts_card.html' %}   

  <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация</a></p>
  <p>{% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
     {% endif %} </p>  
  {% if not forloop.last %}<hr>{% endif %}   
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
 
{% endblock %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}<title>{{group}}</title>{% endblock %} 

{% block content %}
    
  <h1>{{group}}</h1>
  <p>
    {{ group.description }}
  </p>
  
{% for post in page_obj %}

{% include 'includes/posts_card.html' %}

{% endfor %} 
{% include 'posts/includes/paginator.html' %}
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}<title>Последние обновления на сайте</title>{% endblock %} 
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

{% include 'includes/switcher.html' %}  
<h3>Последние обновления на сайте</h3>

{% for post in page_obj %}

{% include 'includes/posts_card.html' %}   

  <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация</a></p>
  <p>{% if post.group %}  
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
     {% endif %}</p>  
  {% if not forloop.last %}<hr>{% endif %}   
{% endfor %} 

{% include 'posts/includes/paginator.html' %}

{% endblock %}   

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}<title>{{post.text.title|truncatechars:30}}</title>{% endblock %}
{% block content %}
  <div class="row">    
    <aside class="col-12 col-md-3">     
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}  
        </li>
           
          <li class="list-group-item">
            Группа: {{ post.group }}            
            {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>  
            {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post.author.posts.count }}<span>  </span> 
        </li>
        <li class="list-group-item">            
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>           
        </li>        
      </ul>
    </aside>     
    <article class="col-12 col-md-9 shadow-sm">  
    {% thumbnail post.image "960x600" crop="center" upscale=True as im %}
     <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}           
      <p>
        {{ post.text }}       
      </p>
    {% if post.author == user %}
      <div class="col-md-6 offset-md-12">
        <a href="{% url 'posts:post_edit' post.id %}">
          <button type="submit" class="btn btn-primary">
            Редактировать 
          </button>
        </a>
      </div> 
    {% endif %}                   
    </article>                   
        {% include 'includes/comments.html' %}      
  </div>    
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}<title>Профайл пользователя {{author.get_full_name}}</title>{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя: {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if user != author and user.is_authenticated %}
   {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
   {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
       Подписаться 
      </a>
    {% endif %}
  {% endif %}  
</div>
{% for post in page_obj %}

{% include 'includes/posts_card.html' %} 

  <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация</a></p>
      
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>    
  {% endif %} 
    
{% endfor %}

  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}
  

    
    